# Generated by Django 5.2.17 on 2026-09-03 09:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('total_sessions', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('file_url', models.CharField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='students.student')),
            ],
            options={
                'verbose_name': 'Báo cáo học phí',
                'constraints': [models.UniqueConstraint(fields=('student', 'month', 'year'), name='unique_report_per_student_month')],
            },
        ),
    ]
