# Generated by Django 5.2.17 on 2026-09-03 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('price_per_session', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('inactive', 'Đã nghỉ')], default='active', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Học viên',
            },
        ),
    ]
