# Generated by Django 5.2.17 on 2026-09-03 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_refresh_token', models.TextField(blank=True, default='')),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Giáo viên',
            },
        ),
    ]
