# Generated by Django 5.2.17 on 2026-09-03 09:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Nghỉ')], max_length=10)),
                ('is_billable', models.BooleanField(editable=False)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='scheduling.session')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
            },
        ),
    ]
